version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - medhelm-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/medhelm
      - REDIS_URL=redis://redis:6379
    env_file:
      - server/.env
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - medhelm-network

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - medhelm-network

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - medhelm-network

volumes:
  mongodb_data:
  redis_data:

networks:
  medhelm-network:
    driver: bridge
