name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Frontend Build
        run: |
          npm ci
          npm run build

      - name: Docker Login (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Backend Image
        run: |
          GIT_SHA=${{ github.sha }}
          docker build -t ghcr.io/${{ github.repository_owner }}/medhelm-backend:latest -t ghcr.io/${{ github.repository_owner }}/medhelm-backend:${GIT_SHA} ./eCommerce-Backend

      - name: Build Frontend Image
        run: |
          GIT_SHA=${{ github.sha }}
          docker build -t ghcr.io/${{ github.repository_owner }}/medhelm-frontend:latest -t ghcr.io/${{ github.repository_owner }}/medhelm-frontend:${GIT_SHA} .

      - name: Push Images
        run: |
          GIT_SHA=${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/medhelm-backend:latest
          docker push ghcr.io/${{ github.repository_owner }}/medhelm-backend:${GIT_SHA}
          docker push ghcr.io/${{ github.repository_owner }}/medhelm-frontend:latest
          docker push ghcr.io/${{ github.repository_owner }}/medhelm-frontend:${GIT_SHA}

  # Optional deploy job (placeholder)
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: false  # Set to true and configure steps for your server/CDN
    steps:
      - name: Placeholder
        run: echo "Implement server deployment (SSH, k8s, etc.)"
